ALTER TABLE "InvoiceItem" ADD COLUMN "lineType" TEXT NOT NULL DEFAULT 'PRODUCT';
ALTER TABLE "QuotationItem" ADD COLUMN "lineType" TEXT NOT NULL DEFAULT 'PRODUCT';

ALTER TABLE "InvoiceItem" ALTER COLUMN "productId" DROP NOT NULL;
ALTER TABLE "QuotationItem" ALTER COLUMN "productId" DROP NOT NULL;
