ALTER TABLE "InvoiceItem" ADD COLUMN "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 0.1;
ALTER TABLE "InvoiceItem" ADD COLUMN "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "QuotationItem" ADD COLUMN "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 0.1;
ALTER TABLE "QuotationItem" ADD COLUMN "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
