// Lao administrative divisions seed data
// Provinces (18 total) and their districts
// Source: Standard Lao administrative organization

export type ProvinceSeed = {
  code: string;
  name: string;
  nameEn: string;
  districts: { code: string; name: string; nameEn: string }[];
};

export const PROVINCES: ProvinceSeed[] = [
  {
    code: "VTE",
    name: "ນະຄອນຫຼວງວຽງຈັນ",
    nameEn: "Vientiane Capital",
    districts: [
      { code: "VTE-01", name: "ຈັນທະບູລີ", nameEn: "Chanthabouly" },
      { code: "VTE-02", name: "ສີໂຄດຕະບອງ", nameEn: "Sikhottabong" },
      { code: "VTE-03", name: "ໄຊເສດຖາ", nameEn: "Xaysetha" },
      { code: "VTE-04", name: "ສີສັດຕະນາກ", nameEn: "Sisattanak" },
      { code: "VTE-05", name: "ນາຊາຍທອງ", nameEn: "Naxaithong" },
      { code: "VTE-06", name: "ໄຊທານີ", nameEn: "Xaythany" },
      { code: "VTE-07", name: "ຫາດຊາຍຟອງ", nameEn: "Hatxayfong" },
      { code: "VTE-08", name: "ສັງທອງ", nameEn: "Sangthong" },
      { code: "VTE-09", name: "ປາກງື່ມ", nameEn: "Pakngum" },
    ],
  },
  {
    code: "PSL",
    name: "ຜົ້ງສາລີ",
    nameEn: "Phongsaly",
    districts: [
      { code: "PSL-01", name: "ຜົ້ງສາລີ", nameEn: "Phongsaly" },
      { code: "PSL-02", name: "ໃໝ່", nameEn: "May" },
      { code: "PSL-03", name: "ຂວາ", nameEn: "Khoua" },
      { code: "PSL-04", name: "ສຳພັນ", nameEn: "Samphan" },
      { code: "PSL-05", name: "ບຸນເໜືອ", nameEn: "Boun-Neua" },
      { code: "PSL-06", name: "ບຸນໃຕ້", nameEn: "Boun-Tay" },
      { code: "PSL-07", name: "ຍອດອູ", nameEn: "Yot-Ou" },
    ],
  },
  {
    code: "LNT",
    name: "ຫລວງນ້ຳທາ",
    nameEn: "Luangnamtha",
    districts: [
      { code: "LNT-01", name: "ຫລວງນ້ຳທາ", nameEn: "Luangnamtha" },
      { code: "LNT-02", name: "ສິງ", nameEn: "Sing" },
      { code: "LNT-03", name: "ລອງ", nameEn: "Long" },
      { code: "LNT-04", name: "ວຽງພູຄາ", nameEn: "Viengphoukha" },
      { code: "LNT-05", name: "ນາແລ", nameEn: "Nalae" },
    ],
  },
  {
    code: "ODX",
    name: "ອຸດົມໄຊ",
    nameEn: "Oudomxay",
    districts: [
      { code: "ODX-01", name: "ໄຊ", nameEn: "Xay" },
      { code: "ODX-02", name: "ຫລາ", nameEn: "La" },
      { code: "ODX-03", name: "ນາໝໍ້", nameEn: "Namor" },
      { code: "ODX-04", name: "ງາ", nameEn: "Nga" },
      { code: "ODX-05", name: "ແບ່ງ", nameEn: "Beng" },
      { code: "ODX-06", name: "ຫົງສາ", nameEn: "Houn" },
      { code: "ODX-07", name: "ປາກແບ່ງ", nameEn: "Pakbeng" },
    ],
  },
  {
    code: "BKO",
    name: "ບໍ່ແກ້ວ",
    nameEn: "Bokeo",
    districts: [
      { code: "BKO-01", name: "ຫ້ວຍຊາຍ", nameEn: "Houayxay" },
      { code: "BKO-02", name: "ຕົ້ນເຜິ້ງ", nameEn: "Tonpheung" },
      { code: "BKO-03", name: "ເມິງ", nameEn: "Meung" },
      { code: "BKO-04", name: "ປາກທາ", nameEn: "Paktha" },
      { code: "BKO-05", name: "ຜາອຸດົມ", nameEn: "Pha-Oudom" },
    ],
  },
  {
    code: "LPB",
    name: "ຫລວງພະບາງ",
    nameEn: "Luangprabang",
    districts: [
      { code: "LPB-01", name: "ຫລວງພະບາງ", nameEn: "Luangprabang" },
      { code: "LPB-02", name: "ຊຽງເງິນ", nameEn: "Xiengngeun" },
      { code: "LPB-03", name: "ນານ", nameEn: "Nan" },
      { code: "LPB-04", name: "ປາກອູ", nameEn: "Pak-Ou" },
      { code: "LPB-05", name: "ນຳ້ບາກ", nameEn: "Nambak" },
      { code: "LPB-06", name: "ງອຍ", nameEn: "Ngoy" },
      { code: "LPB-07", name: "ປາກແຊງ", nameEn: "Pakxeng" },
      { code: "LPB-08", name: "ໂພນໄຊ", nameEn: "Phonxay" },
      { code: "LPB-09", name: "ຈອມເພັດ", nameEn: "Chomphet" },
      { code: "LPB-10", name: "ວຽງຄຳ", nameEn: "Viengkham" },
      { code: "LPB-11", name: "ພູຄູນ", nameEn: "Phoukhoun" },
      { code: "LPB-12", name: "ໂພນທອງ", nameEn: "Phonthong" },
    ],
  },
  {
    code: "HPN",
    name: "ຫົວພັນ",
    nameEn: "Houaphanh",
    districts: [
      { code: "HPN-01", name: "ຊຳເໜືອ", nameEn: "Xamneua" },
      { code: "HPN-02", name: "ຊຽງຄໍ້", nameEn: "Xiengkho" },
      { code: "HPN-03", name: "ຫົວເມືອງ", nameEn: "Houameuang" },
      { code: "HPN-04", name: "ຮ້ຽມ", nameEn: "Hiam" },
      { code: "HPN-05", name: "ວຽງໄຊ", nameEn: "Viengxay" },
      { code: "HPN-06", name: "ຊຳໃຕ້", nameEn: "Xamtay" },
      { code: "HPN-07", name: "ສົບເບົາ", nameEn: "Sobbao" },
      { code: "HPN-08", name: "ແອດ", nameEn: "Aed" },
    ],
  },
  {
    code: "XYL",
    name: "ໄຊຍະບູລີ",
    nameEn: "Xayaboury",
    districts: [
      { code: "XYL-01", name: "ໄຊຍະບູລີ", nameEn: "Xayaboury" },
      { code: "XYL-02", name: "ຄອບ", nameEn: "Khop" },
      { code: "XYL-03", name: "ຫົງສາ", nameEn: "Hongsa" },
      { code: "XYL-04", name: "ງື່ນ", nameEn: "Ngeun" },
      { code: "XYL-05", name: "ຊຽງຮ່ອນ", nameEn: "Xienghon" },
      { code: "XYL-06", name: "ພຽງ", nameEn: "Phiang" },
      { code: "XYL-07", name: "ປາກລາຍ", nameEn: "Paklay" },
      { code: "XYL-08", name: "ແກ່ນທ້າວ", nameEn: "Kenthao" },
      { code: "XYL-09", name: "ບໍ່ແຕນ", nameEn: "Botene" },
      { code: "XYL-10", name: "ທົ່ງມີໄຊ", nameEn: "Thongmyxay" },
    ],
  },
  {
    code: "XKH",
    name: "ຊຽງຂວາງ",
    nameEn: "Xiengkhouang",
    districts: [
      { code: "XKH-01", name: "ແປກ", nameEn: "Pek" },
      { code: "XKH-02", name: "ກຳ", nameEn: "Kham" },
      { code: "XKH-03", name: "ໜອງແຫດ", nameEn: "Nonghet" },
      { code: "XKH-04", name: "ຄູນ", nameEn: "Khoune" },
      { code: "XKH-05", name: "ໝອກໃໝ່", nameEn: "Mok-May" },
      { code: "XKH-06", name: "ພູກູດ", nameEn: "Phoukout" },
      { code: "XKH-07", name: "ຜາໄຊ", nameEn: "Phaxay" },
    ],
  },
  {
    code: "VTN",
    name: "ວຽງຈັນ",
    nameEn: "Vientiane Province",
    districts: [
      { code: "VTN-01", name: "ໂພນໂຮງ", nameEn: "Phonhong" },
      { code: "VTN-02", name: "ທຸລະຄົມ", nameEn: "Thoulakhom" },
      { code: "VTN-03", name: "ແກ້ວອຸດົມ", nameEn: "Keo-Oudom" },
      { code: "VTN-04", name: "ກາສີ", nameEn: "Kasy" },
      { code: "VTN-05", name: "ວັງວຽງ", nameEn: "Vangvieng" },
      { code: "VTN-06", name: "ເຟືອງ", nameEn: "Feuang" },
      { code: "VTN-07", name: "ຊະນະຄາມ", nameEn: "Xanakham" },
      { code: "VTN-08", name: "ແມດ", nameEn: "Met" },
      { code: "VTN-09", name: "ວຽງຄຳ", nameEn: "Viengkham" },
      { code: "VTN-10", name: "ຫີນເຫີບ", nameEn: "Hinheup" },
      { code: "VTN-11", name: "ໝື່ນ", nameEn: "Meun" },
    ],
  },
  {
    code: "BKX",
    name: "ບໍລິຄຳໄຊ",
    nameEn: "Bolikhamxay",
    districts: [
      { code: "BKX-01", name: "ປາກຊັນ", nameEn: "Paksane" },
      { code: "BKX-02", name: "ທ່າພະບາດ", nameEn: "Thaphabath" },
      { code: "BKX-03", name: "ປາກກະດິງ", nameEn: "Pakkading" },
      { code: "BKX-04", name: "ບໍລິຄັນ", nameEn: "Borikhane" },
      { code: "BKX-05", name: "ຄຳເກີດ", nameEn: "Khamkeut" },
      { code: "BKX-06", name: "ວຽງທອງ", nameEn: "Viengthong" },
      { code: "BKX-07", name: "ໄຊຈຳພອນ", nameEn: "Xaychamphone" },
    ],
  },
  {
    code: "KMN",
    name: "ຄຳມ່ວນ",
    nameEn: "Khammouane",
    districts: [
      { code: "KMN-01", name: "ທ່າແຂກ", nameEn: "Thakhek" },
      { code: "KMN-02", name: "ມະຫາໄຊ", nameEn: "Mahaxay" },
      { code: "KMN-03", name: "ໜອງບົກ", nameEn: "Nongbok" },
      { code: "KMN-04", name: "ຫີນບູນ", nameEn: "Hinboun" },
      { code: "KMN-05", name: "ຍົມມະລາດ", nameEn: "Yommalath" },
      { code: "KMN-06", name: "ບົວລະພາ", nameEn: "Boualapha" },
      { code: "KMN-07", name: "ນາກາຍ", nameEn: "Nakai" },
      { code: "KMN-08", name: "ເຊບັ້ງໄຟ", nameEn: "Xebangfay" },
      { code: "KMN-09", name: "ໄຊບົວທອງ", nameEn: "Xaybouathong" },
      { code: "KMN-10", name: "ຄູນຄຳ", nameEn: "Khounkham" },
    ],
  },
  {
    code: "SVK",
    name: "ສະຫວັນນະເຂດ",
    nameEn: "Savannakhet",
    districts: [
      { code: "SVK-01", name: "ໄກສອນພົມວິຫານ", nameEn: "Kaysone Phomvihane" },
      { code: "SVK-02", name: "ອຸທຸມພອນ", nameEn: "Outhoumphone" },
      { code: "SVK-03", name: "ອາດສະພັງທອງ", nameEn: "Atsaphangthong" },
      { code: "SVK-04", name: "ພີນ", nameEn: "Phine" },
      { code: "SVK-05", name: "ເຊໂປນ", nameEn: "Sepone" },
      { code: "SVK-06", name: "ນອງ", nameEn: "Nong" },
      { code: "SVK-07", name: "ທະປາງທອງ", nameEn: "Thapangthong" },
      { code: "SVK-08", name: "ສອງຄອນ", nameEn: "Songkhone" },
      { code: "SVK-09", name: "ຈຳພອນ", nameEn: "Champhone" },
      { code: "SVK-10", name: "ຊົນບູລີ", nameEn: "Xonbuly" },
      { code: "SVK-11", name: "ໄຊບູລີ", nameEn: "Xayboury" },
      { code: "SVK-12", name: "ວິລະບູລີ", nameEn: "Vilabouly" },
      { code: "SVK-13", name: "ອາດສະພອນ", nameEn: "Atsaphone" },
      { code: "SVK-14", name: "ໄຊພູທອງ", nameEn: "Xayphouthong" },
      { code: "SVK-15", name: "ພະລານໄຊ", nameEn: "Phalanxay" },
    ],
  },
  {
    code: "SLV",
    name: "ສາລະວັນ",
    nameEn: "Salavan",
    districts: [
      { code: "SLV-01", name: "ສາລະວັນ", nameEn: "Salavan" },
      { code: "SLV-02", name: "ຕະໂອ້ຍ", nameEn: "Ta-Oy" },
      { code: "SLV-03", name: "ຕຸ້ມລານ", nameEn: "Toumlane" },
      { code: "SLV-04", name: "ລະຄອນເພັງ", nameEn: "Lakhonpheng" },
      { code: "SLV-05", name: "ວາປີ", nameEn: "Vapy" },
      { code: "SLV-06", name: "ຄົງເຊໂດນ", nameEn: "Khongxedone" },
      { code: "SLV-07", name: "ເລົ່າງາມ", nameEn: "Laongam" },
      { code: "SLV-08", name: "ສະໝ້ວຍ", nameEn: "Samuoy" },
    ],
  },
  {
    code: "SKO",
    name: "ເຊກອງ",
    nameEn: "Sekong",
    districts: [
      { code: "SKO-01", name: "ລະມາມ", nameEn: "Lamam" },
      { code: "SKO-02", name: "ກະລື້ມ", nameEn: "Kaleum" },
      { code: "SKO-03", name: "ດາກຈຶງ", nameEn: "Dakcheung" },
      { code: "SKO-04", name: "ທ່າແຕງ", nameEn: "Thateng" },
    ],
  },
  {
    code: "CHP",
    name: "ຈຳປາສັກ",
    nameEn: "Champasak",
    districts: [
      { code: "CHP-01", name: "ປາກເຊ", nameEn: "Pakse" },
      { code: "CHP-02", name: "ຊະນະສົມບູນ", nameEn: "Xanasomboun" },
      { code: "CHP-03", name: "ບາຈຽງຈະເລີນສຸກ", nameEn: "Bachiengchaleunsuk" },
      { code: "CHP-04", name: "ປາກຊ່ອງ", nameEn: "Paksong" },
      { code: "CHP-05", name: "ປະທຸມພອນ", nameEn: "Pathoumphone" },
      { code: "CHP-06", name: "ໂພນທອງ", nameEn: "Phonthong" },
      { code: "CHP-07", name: "ຈຳປາສັກ", nameEn: "Champasak" },
      { code: "CHP-08", name: "ສຸຂຸມາ", nameEn: "Soukhouma" },
      { code: "CHP-09", name: "ມຸນລະປະໂມກ", nameEn: "Moonlapamok" },
      { code: "CHP-10", name: "ໂຂງ", nameEn: "Khong" },
    ],
  },
  {
    code: "ATP",
    name: "ອັດຕະປື",
    nameEn: "Attapeu",
    districts: [
      { code: "ATP-01", name: "ສາມັກຄີໄຊ", nameEn: "Samakkhixay" },
      { code: "ATP-02", name: "ສະໜາມໄຊ", nameEn: "Sanamxay" },
      { code: "ATP-03", name: "ໄຊເສດຖາ", nameEn: "Xaysetha" },
      { code: "ATP-04", name: "ຊານໄຊ", nameEn: "Sanxay" },
      { code: "ATP-05", name: "ພູວົງ", nameEn: "Phouvong" },
    ],
  },
  {
    code: "XSB",
    name: "ໄຊສົມບູນ",
    nameEn: "Xaysomboun",
    districts: [
      { code: "XSB-01", name: "ອານຸວົງ", nameEn: "Anouvong" },
      { code: "XSB-02", name: "ລ້ອງແຈ້ງ", nameEn: "Longchaeng" },
      { code: "XSB-03", name: "ລ້ອງສານ", nameEn: "Longsan" },
      { code: "XSB-04", name: "ທ່າທອມ", nameEn: "Thathom" },
      { code: "XSB-05", name: "ຫົມ", nameEn: "Hom" },
    ],
  },
];
