ALTER TABLE "BillingInvoiceItem" ADD COLUMN "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 0.1;
ALTER TABLE "BillingInvoiceItem" ADD COLUMN "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "BillingQuoteItem" ADD COLUMN "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 0.1;
ALTER TABLE "BillingQuoteItem" ADD COLUMN "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
