ALTER TABLE "RecurringInvoiceItem" ADD COLUMN "lineType" TEXT NOT NULL DEFAULT 'PRODUCT';
ALTER TABLE "RecurringInvoiceItem" ADD COLUMN "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 0.1;
ALTER TABLE "RecurringInvoiceItem" ADD COLUMN "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "RecurringInvoiceItem" ALTER COLUMN "productId" DROP NOT NULL;
